[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.packages.find]
include = ["data_frames*"]
exclude = ["data", "assets", "notebooks"]