[tool.poetry]
name = "eosframes"
version = "0.1.0"
description = "Ersilia utilities for working with tabular output data"
authors = ["Ersilia Open Source Initiative <hello@ersilia.io>"]

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.packages]
include = "eosframes"
