name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pypi-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4.0.0

      - name: Install poetry-dynamic-versioning plugin
        run: poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Configure PyPI credentials
        run: |
          poetry config pypi-token.pypi "${{ secrets.ALL_PYPI_PROJECTS_API_TOKEN }}"

      - name: Build and publish to PyPI
        run: poetry publish --build
